/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package core;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.InputValidator;
import util.LoggerUtil;


/**
 *
 * @author Hydron
 */
public class BAdd extends javax.swing.JFrame {

    /**
     * Creates new form BAdd
     */
    public BAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bw_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bw_address = new javax.swing.JTextField();
        bw_amount = new javax.swing.JTextField();
        bw_email = new javax.swing.JTextField();
        bw_id = new javax.swing.JTextField();
        bw_contact = new javax.swing.JTextField();
        bw_borrowed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setText("Borrower Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 242, 180, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setText("Borrower Contact");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 292, 180, -1));

        bw_name.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bw_nameKeyTyped(evt);
            }
        });
        getContentPane().add(bw_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 142, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setText("Book Borrowed");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, -1));

        bw_address.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(bw_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 192, 160, 30));

        bw_amount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bw_amountKeyTyped(evt);
            }
        });
        getContentPane().add(bw_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 392, 160, 30));

        bw_email.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(bw_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 242, 160, 30));

        bw_id.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bw_idKeyTyped(evt);
            }
        });
        getContentPane().add(bw_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 89, 160, 30));

        bw_contact.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(bw_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 292, 160, 30));

        bw_borrowed.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bw_borrowed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bw_borrowedKeyTyped(evt);
            }
        });
        getContentPane().add(bw_borrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Fine Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("Borrower Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 89, 120, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("Borrower Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 142, 180, -1));

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add-btn.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 140, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("Borrower Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 192, -1, -1));

        jButton3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close-btn.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 170, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add-bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add borrower action
    if (isBorrowerInputValid()) {
            Connection con = null;
            PreparedStatement ps = null;

            // Storing user data entered into the string
            String id = bw_id.getText();
            String name = bw_name.getText();
            String address = bw_address.getText();
            String email = bw_email.getText();
            String contact = bw_contact.getText();
            String borrowed = bw_borrowed.getText();
            String amount = bw_amount.getText();

            // SQL Query
            final String SQL = "INSERT INTO borrowers(BOR_ID, BOR_NAME, BOR_ADDRESS, BOR_EMAIL, BOR_CONTACT, BK_BORROWED, FINE_AMT) VALUES (?, ?, ?, ?, ?, ?, ?)";

            // Performing the Database operation
            try {
                con = Connect.dbconnection();
                ps = con.prepareStatement(SQL);

                ps.setString(1, id);
                ps.setString(2, name);
                ps.setString(3, address);
                ps.setString(4, email);
                ps.setString(5, contact);
                ps.setString(6, borrowed);
                ps.setString(7, amount);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Borrower Added successfully !!", "Success", JOptionPane.INFORMATION_MESSAGE);

                clearBorrowerFields();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Database Operation Failed !!!", "Database ERROR", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.logError("Database operation failed", ex);

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Database driver not found!!!", "Database Driver ERROR", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.logError("Database driver not found", ex);

            }catch (HeadlessException ex) {
              LoggerUtil.logError("Display system no available", ex);
            }finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException e) {
                    LoggerUtil.logError("Failed to close database resources", e);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //close button action on  click
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bw_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bw_idKeyTyped
        // check borrower id
        InputValidator.validateNumericInput(evt, rootPane, "Only numbers are allowed for Borrower ID !!");
    }//GEN-LAST:event_bw_idKeyTyped

    private void bw_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bw_nameKeyTyped
        // check borrower name
        InputValidator.validateCharacterInput(evt, rootPane, "Only character are allowed for Borrower Name !!");
    }//GEN-LAST:event_bw_nameKeyTyped

    private void bw_borrowedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bw_borrowedKeyTyped
        // check borrowed book
        InputValidator.validateNumericInput(evt, rootPane, "Only numbers are allowed for Borrowed Books !!");
    }//GEN-LAST:event_bw_borrowedKeyTyped

    private void bw_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bw_amountKeyTyped
        // check fine amount
        InputValidator.validateNumericInput(evt, rootPane, "Only numbers are allowed for Fine Amount!");
    }//GEN-LAST:event_bw_amountKeyTyped

    private boolean isBorrowerInputValid() {
        if (bw_id.getText().isEmpty() || bw_name.getText().isEmpty() || bw_address.getText().isEmpty() || bw_email.getText().isEmpty() || bw_contact.getText().isEmpty() || bw_borrowed.getText().isEmpty() || bw_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the details !!", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            if (Integer.parseInt(bw_id.getText()) < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Borrower Id", "Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            Double.valueOf(bw_amount.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number format for ID or amount", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return !(!InputValidator.validateEmail(bw_email.getText(), rootPane) || !InputValidator.validateMobileNumber(bw_contact.getText(), rootPane));
    }

    private void clearBorrowerFields() {
        bw_id.setText("");
        bw_name.setText("");
        bw_address.setText("");
        bw_email.setText("");
        bw_contact.setText("");
        bw_borrowed.setText("");
        bw_amount.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            LoggerUtil.logError("Nimbus Look and Feel class not found", ex);
        } catch (InstantiationException ex) {
            LoggerUtil.logError("Unable to instantiate the class ", ex);
        } catch (IllegalAccessException ex) {
            LoggerUtil.logError("Access denied", ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            LoggerUtil.logError("Look and feel not supported by the system", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BAdd j1 = new BAdd();
                ImageIcon img = new ImageIcon(getClass().getResource("/assets/add-borrower-icon.png"));
                j1.setIconImage(img.getImage());
                j1.setTitle("Add Borrower");
                j1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bw_address;
    private javax.swing.JTextField bw_amount;
    private javax.swing.JTextField bw_borrowed;
    private javax.swing.JTextField bw_contact;
    private javax.swing.JTextField bw_email;
    private javax.swing.JTextField bw_id;
    private javax.swing.JTextField bw_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
