/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core;

import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.LoggerUtil;



/**
 *
 * @author Hydron
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        ulab = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        elab = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        mlab = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Page");
        setName("Register"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 227, 206));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1800, 940));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Please");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 52, 1036, 120));

        jPanel2.setBackground(new java.awt.Color(131, 51, 51));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 10));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 20, 1097, -1));

        jPanel3.setBackground(new java.awt.Color(131, 51, 51));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 10));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 184, 1097, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 40)); // NOI18N
        jLabel3.setText("Username :");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 35, 258, -1));

        username.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        username.setName("username"); // NOI18N
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jPanel4.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 46, 300, 47));

        ulab.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ulab.setForeground(new java.awt.Color(255, 0, 0));
        ulab.setText("*");
        ulab.setName("ulab"); // NOI18N
        jPanel4.add(ulab, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 62, 290, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 40)); // NOI18N
        jLabel6.setText("E-Mail       :");
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 137, 258, -1));

        email.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        email.setName("email"); // NOI18N
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 148, 300, 47));

        elab.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        elab.setForeground(new java.awt.Color(255, 0, 0));
        elab.setText("*");
        elab.setName("elab"); // NOI18N
        jPanel4.add(elab, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 164, 290, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 40)); // NOI18N
        jLabel4.setText("Password  :");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 239, 258, -1));

        password.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        password.setName("password"); // NOI18N
        jPanel4.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 250, 300, 47));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 40)); // NOI18N
        jLabel5.setText("Mobile-No :");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 341, 258, -1));

        mobile.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        mobile.setName("mobile"); // NOI18N
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileKeyTyped(evt);
            }
        });
        jPanel4.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 355, 300, 47));

        mlab.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mlab.setForeground(new java.awt.Color(255, 0, 0));
        mlab.setText("*");
        mlab.setName("mlab"); // NOI18N
        jPanel4.add(mlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 368, 290, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Register");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 163, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Log In");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 480, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/register-btn-bg.jpg"))); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 460, 240, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/register-btn-bg.jpg"))); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 460, 240, 80));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 206, 1097, 570));

        jPanel5.setBackground(new java.awt.Color(131, 51, 51));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 10));

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1097, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 796, 1097, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/register-banner.jpg"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 37, 1097, 141));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // Validating username
        String user= username.getText();
        String PATTERN = "^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){0,18}[a-zA-Z0-9]$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(user);
        if(!match.matches())
        {
            ulab.setText("*Username must contain at least 2 characters.");
        }
        else
        {
            ulab.setText(null);
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
        String emailid;
        emailid = "^[a-zA-Z0-9]{2,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(emailid);
        Matcher match = patt.matcher(email.getText());
        if(!match.matches())
        {
            elab.setText("*Email is invalid!");
        }
        else
        {
            elab.setText(null);
        }
    }//GEN-LAST:event_emailKeyTyped

    private void mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyTyped
     
        char keyChar = evt.getKeyChar();
        String value = mobile.getText();
        int length = value.length();

        // Allow backspace and delete for editing
        if (keyChar == '\b' || keyChar == '\u007F') {
            return;
        }

        // Check if the input character is a digit and the length is within the limit
        if (Character.isDigit(keyChar) && length < 10) {
            // If it's the first character, check if it's one of the allowed digits
            if (length == 0) {
                if (keyChar != '6' && keyChar != '7' && keyChar != '8' && keyChar != '9') {
                    mlab.setText("Must start with 6, 7, 8 or 9");
                    evt.consume(); // Prevent the character from being added
                } else {
                    mlab.setText(null);
                }
            } else {    
                mlab.setText(null);
            }
        } else {
            evt.consume(); // Prevent the character from being added if it's not a digit or length exceeds 10
        }
    }//GEN-LAST:event_mobileKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // validating password
        String passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{5,16}$";
        Pattern pattern = Pattern.compile(passwordRegex);
        
        //validating form by checking whether user has fill all data or not
        if(username.getText().equals("")||mobile.getText().equals("") || password.getText().equals("")||email.getText().equals(""))
        {
            //showing error message
            JOptionPane.showMessageDialog(this, " Please enter data !!!", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            
            Matcher matcher = pattern.matcher(password.getText());
            if(!matcher.matches()){
                JOptionPane.showMessageDialog(null,"Password Length must be in 5-16 with one lowercase, uppercase letter and one number", "Invalid Password", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try{
                if(ulab.getText()==null && elab.getText()==null && mlab.getText()== null)
                {
                    PreparedStatement pst = null;
                    String query = "insert into users values(?,?,?,?)";
                    Connection con = Connect.dbconnection();
                    pst=con.prepareStatement(query);
                    pst.setString(1, username.getText());
                    pst.setString(2, email.getText());
                    pst.setString(4, mobile.getText());
                    pst.setString(3, password.getText());
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this,"Registered successfully !!","Success",JOptionPane.INFORMATION_MESSAGE);
                    //clearing the text fields
                    username.setText("");
                    mobile.setText("");
                    password.setText("");
                    email.setText("");
                    email.setEditable(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid details entered!", "ERROR", JOptionPane.WARNING_MESSAGE);
                    //clearing the text fields
                    username.setText("");
                    mobile.setText("");
                    password.setText("");
                    email.setText("");
                    email.setEditable(true);
                }

            }catch (SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Database Operation Failed !!!", "Database ERROR", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.logError("Database operation Failed", ex);
                
            }catch (ClassNotFoundException ex){
                JOptionPane.showMessageDialog(rootPane, "Database driver not found!!!", "Database Driver ERROR", JOptionPane.ERROR_MESSAGE);
                LoggerUtil.logError("Database driver not found", ex);
                
            }catch (HeadlessException ex){
                LoggerUtil.logError("Display system no available", ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login loginPage = new Login();
        ImageIcon img;
        img = new ImageIcon(getClass().getResource("/assets/login-icon.png"));
        loginPage.setTitle("Login Page");
        loginPage.setIconImage(img.getImage());
        loginPage.setVisible(true);//displaying Login_Form
        dispose();//close current Register Page after Opening the Login Page
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            LoggerUtil.logError("Nimbus Look and Feel class not found", ex);
        } catch (InstantiationException ex) {
            LoggerUtil.logError("Unable to instantiate the class ", ex);
        } catch (IllegalAccessException ex) {
            LoggerUtil.logError("Access denied", ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            LoggerUtil.logError("Look and feel not supported by the system", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Register registerPage = new Register();
                registerPage.setTitle("Register Page");
                ImageIcon icon = new ImageIcon(getClass().getResource("/assets/register-icon.png"));
                registerPage.setIconImage(icon.getImage());
                registerPage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elab;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel mlab;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel ulab;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
